<a href="https://colab.research.google.com/github/Praneethcruzon/Data-Analytics-Laboratory/blob/master/kerasANNsample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Simple ANN using keras

*   Sequential creates a sequence of layers
*   Dense creates a fully connected network



In [2]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

Using TensorFlow backend.


In [0]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler,OneHotEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split

In [0]:
iris = load_iris()
print(iris)

In [0]:
print(iris.feature_names)
print(iris.target_names)
#print(iris.DESCR)
#print(iris.data)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [0]:
input_data = iris.data

In [12]:
target_class = iris.target
#iris['target']
target_class

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

###Use z-score normalization to convert data with mean 0 and variance 1

In [22]:
scaler = MinMaxScaler([-1,1])
input_scaled = scaler.fit_transform(input_data)
print(input_scaled)

[[-5.55555556e-01  2.50000000e-01 -8.64406780e-01 -9.16666667e-01]
 [-6.66666667e-01 -1.66666667e-01 -8.64406780e-01 -9.16666667e-01]
 [-7.77777778e-01  0.00000000e+00 -8.98305085e-01 -9.16666667e-01]
 [-8.33333333e-01 -8.33333333e-02 -8.30508475e-01 -9.16666667e-01]
 [-6.11111111e-01  3.33333333e-01 -8.64406780e-01 -9.16666667e-01]
 [-3.88888889e-01  5.83333333e-01 -7.62711864e-01 -7.50000000e-01]
 [-8.33333333e-01  1.66666667e-01 -8.64406780e-01 -8.33333333e-01]
 [-6.11111111e-01  1.66666667e-01 -8.30508475e-01 -9.16666667e-01]
 [-9.44444444e-01 -2.50000000e-01 -8.64406780e-01 -9.16666667e-01]
 [-6.66666667e-01 -8.33333333e-02 -8.30508475e-01 -1.00000000e+00]
 [-3.88888889e-01  4.16666667e-01 -8.30508475e-01 -9.16666667e-01]
 [-7.22222222e-01  1.66666667e-01 -7.96610169e-01 -9.16666667e-01]
 [-7.22222222e-01 -1.66666667e-01 -8.64406780e-01 -1.00000000e+00]
 [-1.00000000e+00 -1.66666667e-01 -9.66101695e-01 -1.00000000e+00]
 [-1.66666667e-01  6.66666667e-01 -9.32203390e-01 -9.16666667e

In [23]:
# One hot encoding
enc = OneHotEncoder()
hot_target_class = enc.fit_transform(target_class[:, np.newaxis]).toarray()
hot_target_class

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

###Split into training and testing data

In [0]:
x_train,x_test,y_train,y_test = train_test_split(input_scaled,hot_target_class,test_size=0.3)
#x_train
#x_test

###Create model

In [26]:
model = Sequential()

W0820 05:52:17.604170 140324248418176 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



###Can add any number of layers using model.add


*   Compulsorily the first add function must have the parameter input_dim
*   Default activation is linear function



In [27]:
h1 = model.add(Dense(6,activation="relu",input_dim=4))
h2=model.add(Dense(5,activation="relu"))
h3=model.add(Dense(7,activation="relu"))
o = model.add(Dense(3,activation="softmax"))



W0820 05:52:20.008306 140324248418176 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0820 05:52:20.028331 140324248418176 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [0]:
###Compile model

In [29]:
model.compile(loss="categorical_crossentropy",optimizer="Adam",metrics=['accuracy'])

W0820 05:52:39.027478 140324248418176 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0820 05:52:39.069175 140324248418176 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [30]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 30        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 35        
_________________________________________________________________
dense_3 (Dense)              (None, 7)                 42        
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 24        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


###Fit model

*   Epoch - how many passes through the training dataset
*   Batch - how many samples to consider before updating the weights



In [31]:
model.fit(x_train,y_train,batch_size=10,epochs=50)

W0820 05:52:45.917338 140324248418176 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0820 05:52:45.982973 140324248418176 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/50
105/105 [==============================] - 1s 8ms/step - loss: 0.9995 - acc: 0.4000
Epoch 2/50
105/105 [==============================] - 0s 209us/step - loss: 0.9728 - acc: 0.4190
Epoch 3/50
105/105 [==============================] - 0s 201us/step - loss: 0.9488 - acc: 0.4381
Epoch 4/50
105/105 [==============================] - 0s 208us/step - loss: 0.9228 - acc: 0.4571
Epoch 5/50
105/105 [==============================] - 0s 192us/step - loss: 0.8974 - acc: 0.4667
Epoch 6/50
105/105 [==============================] - 0s 214us/step - loss: 0.8709 - acc: 0.5048
Epoch 7/50
105/105 [==============================] - 0s 185us/step - loss: 0.8462 - acc: 0.5143
Epoch 8/50
105/105 [==============================] - 0s 177us/step - loss: 0.8183 - acc: 0.5619
Epoch 9/50
105/105 [==============================] - 0s 206us/step - loss: 0.7906 - acc: 0.6571
Epoch 10/50
105/105 [==============================] - 0s 186us/step - loss: 0.7619 - acc: 0.7143
Epoch 11/50
105/105 [==========

In [32]:
 score = model.evaluate(x_test,y_test, verbose=0)
 print('Test loss:', score[0])
 print('Test accuracy:', score[1])

Test loss: 0.34025471674071417
Test accuracy: 0.933333334657881
