<a href="https://colab.research.google.com/github/Praneethcruzon/Data-Analytics-Laboratory/blob/master/NeuralNetworkModelTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler,OneHotEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split

In [0]:
inputdata = np.array([[1,0,1]])
targetdata = np.array([[1,0]])

In [0]:
model = Sequential()
h1 = model.add(Dense(2,activation="sigmoid",input_dim=3))
h2=model.add(Dense(3,activation="sigmoid"))
o = model.add(Dense(2,activation="linear"))

In [0]:
w1 = np.zeros((3, 2))
b1 = np.zeros((2,))
w2 = np.zeros((2, 3))
b2 = np.zeros((3,))
w3 = np.zeros((3, 2))
b3 = np.zeros((2,))

In [0]:
w1 = np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
b1 = np.array([-0.4,0.2])
w2 = np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2]])
b2 = np.array([0.1,0.1,0.2])
w3 = np.array([[0.3,0.2],[-0.5,0.5],[-0.7,0.2]])
b3 = np.array([0.1,0.2])

In [0]:
model.set_weights([w1,b1,w2,b2,w3,b3])

In [0]:
import keras
custom = keras.optimizers.Adam(lr=0.9)

In [85]:
model.summary()
model.compile(loss="mean_squared_error",optimizer= custom,metrics=['accuracy'])
model.fit(inputdata,targetdata,epochs=200)


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 2)                 8         
_________________________________________________________________
dense_26 (Dense)             (None, 3)                 9         
_________________________________________________________________
dense_27 (Dense)             (None, 2)                 8         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________
Epoch 1/200
1/1 [==============================] - 1s 1s/step - loss: 1.2395 - acc: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6230 - acc: 1.0000
Epoch 3/200
1/1 [==============================] - 0s 3ms/step - loss: 0.4149 - acc: 1.0000
Epoch 4/200
1/1 [==============================] - 0s 3ms/step - loss: 0.0618 - acc: 1.0000
Epoch 5/200
1/1 [======================

In [50]:
model.get_weights()

[array([[ 0.19925591, -0.29925603],
        [ 0.4       ,  0.1       ],
        [-0.5007441 ,  0.200744  ]], dtype=float32),
 array([-0.4007441,  0.200744 ], dtype=float32),
 array([[-0.29925597,  0.1992559 ,  0.5992559 ],
        [-0.19925593, -0.10074412, -0.20074412]], dtype=float32),
 array([0.10074411, 0.09925587, 0.19925588], dtype=float32),
 array([[ 0.30074415,  0.19925587],
        [-0.49925587,  0.49925587],
        [-0.6992559 ,  0.19925587]], dtype=float32),
 array([0.10074414, 0.19925587], dtype=float32)]